# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sadra/simulation/astra-sim-master/astra-sim

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sadra/simulation/astra-sim-master/astra-sim

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sadra/simulation/astra-sim-master/astra-sim/CMakeFiles /home/sadra/simulation/astra-sim-master/astra-sim//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sadra/simulation/astra-sim-master/astra-sim/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AstraSim

# Build rule for target.
AstraSim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AstraSim
.PHONY : AstraSim

# fast build rule for target.
AstraSim/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/build
.PHONY : AstraSim/fast

#=============================================================================
# Target rules for targets named fmt

# Build rule for target.
fmt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fmt
.PHONY : fmt

# fast build rule for target.
fmt/fast:
	$(MAKE) $(MAKESILENT) -f extern/helper/fmt/CMakeFiles/fmt.dir/build.make extern/helper/fmt/CMakeFiles/fmt.dir/build
.PHONY : fmt/fast

#=============================================================================
# Target rules for targets named spdlog

# Build rule for target.
spdlog: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 spdlog
.PHONY : spdlog

# fast build rule for target.
spdlog/fast:
	$(MAKE) $(MAKESILENT) -f extern/helper/spdlog/CMakeFiles/spdlog.dir/build.make extern/helper/spdlog/CMakeFiles/spdlog.dir/build
.PHONY : spdlog/fast

astra-sim/common/Logging.o: astra-sim/common/Logging.cc.o
.PHONY : astra-sim/common/Logging.o

# target to build an object file
astra-sim/common/Logging.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/common/Logging.cc.o
.PHONY : astra-sim/common/Logging.cc.o

astra-sim/common/Logging.i: astra-sim/common/Logging.cc.i
.PHONY : astra-sim/common/Logging.i

# target to preprocess a source file
astra-sim/common/Logging.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/common/Logging.cc.i
.PHONY : astra-sim/common/Logging.cc.i

astra-sim/common/Logging.s: astra-sim/common/Logging.cc.s
.PHONY : astra-sim/common/Logging.s

# target to generate assembly for a file
astra-sim/common/Logging.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/common/Logging.cc.s
.PHONY : astra-sim/common/Logging.cc.s

astra-sim/system/BaseStream.o: astra-sim/system/BaseStream.cc.o
.PHONY : astra-sim/system/BaseStream.o

# target to build an object file
astra-sim/system/BaseStream.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/BaseStream.cc.o
.PHONY : astra-sim/system/BaseStream.cc.o

astra-sim/system/BaseStream.i: astra-sim/system/BaseStream.cc.i
.PHONY : astra-sim/system/BaseStream.i

# target to preprocess a source file
astra-sim/system/BaseStream.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/BaseStream.cc.i
.PHONY : astra-sim/system/BaseStream.cc.i

astra-sim/system/BaseStream.s: astra-sim/system/BaseStream.cc.s
.PHONY : astra-sim/system/BaseStream.s

# target to generate assembly for a file
astra-sim/system/BaseStream.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/BaseStream.cc.s
.PHONY : astra-sim/system/BaseStream.cc.s

astra-sim/system/BasicEventHandlerData.o: astra-sim/system/BasicEventHandlerData.cc.o
.PHONY : astra-sim/system/BasicEventHandlerData.o

# target to build an object file
astra-sim/system/BasicEventHandlerData.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/BasicEventHandlerData.cc.o
.PHONY : astra-sim/system/BasicEventHandlerData.cc.o

astra-sim/system/BasicEventHandlerData.i: astra-sim/system/BasicEventHandlerData.cc.i
.PHONY : astra-sim/system/BasicEventHandlerData.i

# target to preprocess a source file
astra-sim/system/BasicEventHandlerData.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/BasicEventHandlerData.cc.i
.PHONY : astra-sim/system/BasicEventHandlerData.cc.i

astra-sim/system/BasicEventHandlerData.s: astra-sim/system/BasicEventHandlerData.cc.s
.PHONY : astra-sim/system/BasicEventHandlerData.s

# target to generate assembly for a file
astra-sim/system/BasicEventHandlerData.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/BasicEventHandlerData.cc.s
.PHONY : astra-sim/system/BasicEventHandlerData.cc.s

astra-sim/system/CSVWriter.o: astra-sim/system/CSVWriter.cc.o
.PHONY : astra-sim/system/CSVWriter.o

# target to build an object file
astra-sim/system/CSVWriter.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/CSVWriter.cc.o
.PHONY : astra-sim/system/CSVWriter.cc.o

astra-sim/system/CSVWriter.i: astra-sim/system/CSVWriter.cc.i
.PHONY : astra-sim/system/CSVWriter.i

# target to preprocess a source file
astra-sim/system/CSVWriter.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/CSVWriter.cc.i
.PHONY : astra-sim/system/CSVWriter.cc.i

astra-sim/system/CSVWriter.s: astra-sim/system/CSVWriter.cc.s
.PHONY : astra-sim/system/CSVWriter.s

# target to generate assembly for a file
astra-sim/system/CSVWriter.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/CSVWriter.cc.s
.PHONY : astra-sim/system/CSVWriter.cc.s

astra-sim/system/CollectivePhase.o: astra-sim/system/CollectivePhase.cc.o
.PHONY : astra-sim/system/CollectivePhase.o

# target to build an object file
astra-sim/system/CollectivePhase.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/CollectivePhase.cc.o
.PHONY : astra-sim/system/CollectivePhase.cc.o

astra-sim/system/CollectivePhase.i: astra-sim/system/CollectivePhase.cc.i
.PHONY : astra-sim/system/CollectivePhase.i

# target to preprocess a source file
astra-sim/system/CollectivePhase.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/CollectivePhase.cc.i
.PHONY : astra-sim/system/CollectivePhase.cc.i

astra-sim/system/CollectivePhase.s: astra-sim/system/CollectivePhase.cc.s
.PHONY : astra-sim/system/CollectivePhase.s

# target to generate assembly for a file
astra-sim/system/CollectivePhase.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/CollectivePhase.cc.s
.PHONY : astra-sim/system/CollectivePhase.cc.s

astra-sim/system/CollectivePlan.o: astra-sim/system/CollectivePlan.cc.o
.PHONY : astra-sim/system/CollectivePlan.o

# target to build an object file
astra-sim/system/CollectivePlan.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/CollectivePlan.cc.o
.PHONY : astra-sim/system/CollectivePlan.cc.o

astra-sim/system/CollectivePlan.i: astra-sim/system/CollectivePlan.cc.i
.PHONY : astra-sim/system/CollectivePlan.i

# target to preprocess a source file
astra-sim/system/CollectivePlan.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/CollectivePlan.cc.i
.PHONY : astra-sim/system/CollectivePlan.cc.i

astra-sim/system/CollectivePlan.s: astra-sim/system/CollectivePlan.cc.s
.PHONY : astra-sim/system/CollectivePlan.s

# target to generate assembly for a file
astra-sim/system/CollectivePlan.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/CollectivePlan.cc.s
.PHONY : astra-sim/system/CollectivePlan.cc.s

astra-sim/system/CommunicatorGroup.o: astra-sim/system/CommunicatorGroup.cc.o
.PHONY : astra-sim/system/CommunicatorGroup.o

# target to build an object file
astra-sim/system/CommunicatorGroup.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/CommunicatorGroup.cc.o
.PHONY : astra-sim/system/CommunicatorGroup.cc.o

astra-sim/system/CommunicatorGroup.i: astra-sim/system/CommunicatorGroup.cc.i
.PHONY : astra-sim/system/CommunicatorGroup.i

# target to preprocess a source file
astra-sim/system/CommunicatorGroup.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/CommunicatorGroup.cc.i
.PHONY : astra-sim/system/CommunicatorGroup.cc.i

astra-sim/system/CommunicatorGroup.s: astra-sim/system/CommunicatorGroup.cc.s
.PHONY : astra-sim/system/CommunicatorGroup.s

# target to generate assembly for a file
astra-sim/system/CommunicatorGroup.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/CommunicatorGroup.cc.s
.PHONY : astra-sim/system/CommunicatorGroup.cc.s

astra-sim/system/DataSet.o: astra-sim/system/DataSet.cc.o
.PHONY : astra-sim/system/DataSet.o

# target to build an object file
astra-sim/system/DataSet.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/DataSet.cc.o
.PHONY : astra-sim/system/DataSet.cc.o

astra-sim/system/DataSet.i: astra-sim/system/DataSet.cc.i
.PHONY : astra-sim/system/DataSet.i

# target to preprocess a source file
astra-sim/system/DataSet.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/DataSet.cc.i
.PHONY : astra-sim/system/DataSet.cc.i

astra-sim/system/DataSet.s: astra-sim/system/DataSet.cc.s
.PHONY : astra-sim/system/DataSet.s

# target to generate assembly for a file
astra-sim/system/DataSet.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/DataSet.cc.s
.PHONY : astra-sim/system/DataSet.cc.s

astra-sim/system/LogGP.o: astra-sim/system/LogGP.cc.o
.PHONY : astra-sim/system/LogGP.o

# target to build an object file
astra-sim/system/LogGP.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/LogGP.cc.o
.PHONY : astra-sim/system/LogGP.cc.o

astra-sim/system/LogGP.i: astra-sim/system/LogGP.cc.i
.PHONY : astra-sim/system/LogGP.i

# target to preprocess a source file
astra-sim/system/LogGP.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/LogGP.cc.i
.PHONY : astra-sim/system/LogGP.cc.i

astra-sim/system/LogGP.s: astra-sim/system/LogGP.cc.s
.PHONY : astra-sim/system/LogGP.s

# target to generate assembly for a file
astra-sim/system/LogGP.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/LogGP.cc.s
.PHONY : astra-sim/system/LogGP.cc.s

astra-sim/system/MemBus.o: astra-sim/system/MemBus.cc.o
.PHONY : astra-sim/system/MemBus.o

# target to build an object file
astra-sim/system/MemBus.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/MemBus.cc.o
.PHONY : astra-sim/system/MemBus.cc.o

astra-sim/system/MemBus.i: astra-sim/system/MemBus.cc.i
.PHONY : astra-sim/system/MemBus.i

# target to preprocess a source file
astra-sim/system/MemBus.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/MemBus.cc.i
.PHONY : astra-sim/system/MemBus.cc.i

astra-sim/system/MemBus.s: astra-sim/system/MemBus.cc.s
.PHONY : astra-sim/system/MemBus.s

# target to generate assembly for a file
astra-sim/system/MemBus.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/MemBus.cc.s
.PHONY : astra-sim/system/MemBus.cc.s

astra-sim/system/MemEventHandlerData.o: astra-sim/system/MemEventHandlerData.cc.o
.PHONY : astra-sim/system/MemEventHandlerData.o

# target to build an object file
astra-sim/system/MemEventHandlerData.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/MemEventHandlerData.cc.o
.PHONY : astra-sim/system/MemEventHandlerData.cc.o

astra-sim/system/MemEventHandlerData.i: astra-sim/system/MemEventHandlerData.cc.i
.PHONY : astra-sim/system/MemEventHandlerData.i

# target to preprocess a source file
astra-sim/system/MemEventHandlerData.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/MemEventHandlerData.cc.i
.PHONY : astra-sim/system/MemEventHandlerData.cc.i

astra-sim/system/MemEventHandlerData.s: astra-sim/system/MemEventHandlerData.cc.s
.PHONY : astra-sim/system/MemEventHandlerData.s

# target to generate assembly for a file
astra-sim/system/MemEventHandlerData.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/MemEventHandlerData.cc.s
.PHONY : astra-sim/system/MemEventHandlerData.cc.s

astra-sim/system/MemMovRequest.o: astra-sim/system/MemMovRequest.cc.o
.PHONY : astra-sim/system/MemMovRequest.o

# target to build an object file
astra-sim/system/MemMovRequest.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/MemMovRequest.cc.o
.PHONY : astra-sim/system/MemMovRequest.cc.o

astra-sim/system/MemMovRequest.i: astra-sim/system/MemMovRequest.cc.i
.PHONY : astra-sim/system/MemMovRequest.i

# target to preprocess a source file
astra-sim/system/MemMovRequest.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/MemMovRequest.cc.i
.PHONY : astra-sim/system/MemMovRequest.cc.i

astra-sim/system/MemMovRequest.s: astra-sim/system/MemMovRequest.cc.s
.PHONY : astra-sim/system/MemMovRequest.s

# target to generate assembly for a file
astra-sim/system/MemMovRequest.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/MemMovRequest.cc.s
.PHONY : astra-sim/system/MemMovRequest.cc.s

astra-sim/system/MyPacket.o: astra-sim/system/MyPacket.cc.o
.PHONY : astra-sim/system/MyPacket.o

# target to build an object file
astra-sim/system/MyPacket.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/MyPacket.cc.o
.PHONY : astra-sim/system/MyPacket.cc.o

astra-sim/system/MyPacket.i: astra-sim/system/MyPacket.cc.i
.PHONY : astra-sim/system/MyPacket.i

# target to preprocess a source file
astra-sim/system/MyPacket.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/MyPacket.cc.i
.PHONY : astra-sim/system/MyPacket.cc.i

astra-sim/system/MyPacket.s: astra-sim/system/MyPacket.cc.s
.PHONY : astra-sim/system/MyPacket.s

# target to generate assembly for a file
astra-sim/system/MyPacket.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/MyPacket.cc.s
.PHONY : astra-sim/system/MyPacket.cc.s

astra-sim/system/PacketBundle.o: astra-sim/system/PacketBundle.cc.o
.PHONY : astra-sim/system/PacketBundle.o

# target to build an object file
astra-sim/system/PacketBundle.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/PacketBundle.cc.o
.PHONY : astra-sim/system/PacketBundle.cc.o

astra-sim/system/PacketBundle.i: astra-sim/system/PacketBundle.cc.i
.PHONY : astra-sim/system/PacketBundle.i

# target to preprocess a source file
astra-sim/system/PacketBundle.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/PacketBundle.cc.i
.PHONY : astra-sim/system/PacketBundle.cc.i

astra-sim/system/PacketBundle.s: astra-sim/system/PacketBundle.cc.s
.PHONY : astra-sim/system/PacketBundle.s

# target to generate assembly for a file
astra-sim/system/PacketBundle.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/PacketBundle.cc.s
.PHONY : astra-sim/system/PacketBundle.cc.s

astra-sim/system/QueueLevelHandler.o: astra-sim/system/QueueLevelHandler.cc.o
.PHONY : astra-sim/system/QueueLevelHandler.o

# target to build an object file
astra-sim/system/QueueLevelHandler.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/QueueLevelHandler.cc.o
.PHONY : astra-sim/system/QueueLevelHandler.cc.o

astra-sim/system/QueueLevelHandler.i: astra-sim/system/QueueLevelHandler.cc.i
.PHONY : astra-sim/system/QueueLevelHandler.i

# target to preprocess a source file
astra-sim/system/QueueLevelHandler.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/QueueLevelHandler.cc.i
.PHONY : astra-sim/system/QueueLevelHandler.cc.i

astra-sim/system/QueueLevelHandler.s: astra-sim/system/QueueLevelHandler.cc.s
.PHONY : astra-sim/system/QueueLevelHandler.s

# target to generate assembly for a file
astra-sim/system/QueueLevelHandler.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/QueueLevelHandler.cc.s
.PHONY : astra-sim/system/QueueLevelHandler.cc.s

astra-sim/system/QueueLevels.o: astra-sim/system/QueueLevels.cc.o
.PHONY : astra-sim/system/QueueLevels.o

# target to build an object file
astra-sim/system/QueueLevels.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/QueueLevels.cc.o
.PHONY : astra-sim/system/QueueLevels.cc.o

astra-sim/system/QueueLevels.i: astra-sim/system/QueueLevels.cc.i
.PHONY : astra-sim/system/QueueLevels.i

# target to preprocess a source file
astra-sim/system/QueueLevels.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/QueueLevels.cc.i
.PHONY : astra-sim/system/QueueLevels.cc.i

astra-sim/system/QueueLevels.s: astra-sim/system/QueueLevels.cc.s
.PHONY : astra-sim/system/QueueLevels.s

# target to generate assembly for a file
astra-sim/system/QueueLevels.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/QueueLevels.cc.s
.PHONY : astra-sim/system/QueueLevels.cc.s

astra-sim/system/RecvPacketEventHandlerData.o: astra-sim/system/RecvPacketEventHandlerData.cc.o
.PHONY : astra-sim/system/RecvPacketEventHandlerData.o

# target to build an object file
astra-sim/system/RecvPacketEventHandlerData.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/RecvPacketEventHandlerData.cc.o
.PHONY : astra-sim/system/RecvPacketEventHandlerData.cc.o

astra-sim/system/RecvPacketEventHandlerData.i: astra-sim/system/RecvPacketEventHandlerData.cc.i
.PHONY : astra-sim/system/RecvPacketEventHandlerData.i

# target to preprocess a source file
astra-sim/system/RecvPacketEventHandlerData.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/RecvPacketEventHandlerData.cc.i
.PHONY : astra-sim/system/RecvPacketEventHandlerData.cc.i

astra-sim/system/RecvPacketEventHandlerData.s: astra-sim/system/RecvPacketEventHandlerData.cc.s
.PHONY : astra-sim/system/RecvPacketEventHandlerData.s

# target to generate assembly for a file
astra-sim/system/RecvPacketEventHandlerData.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/RecvPacketEventHandlerData.cc.s
.PHONY : astra-sim/system/RecvPacketEventHandlerData.cc.s

astra-sim/system/RendezvousRecvData.o: astra-sim/system/RendezvousRecvData.cc.o
.PHONY : astra-sim/system/RendezvousRecvData.o

# target to build an object file
astra-sim/system/RendezvousRecvData.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/RendezvousRecvData.cc.o
.PHONY : astra-sim/system/RendezvousRecvData.cc.o

astra-sim/system/RendezvousRecvData.i: astra-sim/system/RendezvousRecvData.cc.i
.PHONY : astra-sim/system/RendezvousRecvData.i

# target to preprocess a source file
astra-sim/system/RendezvousRecvData.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/RendezvousRecvData.cc.i
.PHONY : astra-sim/system/RendezvousRecvData.cc.i

astra-sim/system/RendezvousRecvData.s: astra-sim/system/RendezvousRecvData.cc.s
.PHONY : astra-sim/system/RendezvousRecvData.s

# target to generate assembly for a file
astra-sim/system/RendezvousRecvData.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/RendezvousRecvData.cc.s
.PHONY : astra-sim/system/RendezvousRecvData.cc.s

astra-sim/system/RendezvousSendData.o: astra-sim/system/RendezvousSendData.cc.o
.PHONY : astra-sim/system/RendezvousSendData.o

# target to build an object file
astra-sim/system/RendezvousSendData.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/RendezvousSendData.cc.o
.PHONY : astra-sim/system/RendezvousSendData.cc.o

astra-sim/system/RendezvousSendData.i: astra-sim/system/RendezvousSendData.cc.i
.PHONY : astra-sim/system/RendezvousSendData.i

# target to preprocess a source file
astra-sim/system/RendezvousSendData.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/RendezvousSendData.cc.i
.PHONY : astra-sim/system/RendezvousSendData.cc.i

astra-sim/system/RendezvousSendData.s: astra-sim/system/RendezvousSendData.cc.s
.PHONY : astra-sim/system/RendezvousSendData.s

# target to generate assembly for a file
astra-sim/system/RendezvousSendData.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/RendezvousSendData.cc.s
.PHONY : astra-sim/system/RendezvousSendData.cc.s

astra-sim/system/Roofline.o: astra-sim/system/Roofline.cc.o
.PHONY : astra-sim/system/Roofline.o

# target to build an object file
astra-sim/system/Roofline.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/Roofline.cc.o
.PHONY : astra-sim/system/Roofline.cc.o

astra-sim/system/Roofline.i: astra-sim/system/Roofline.cc.i
.PHONY : astra-sim/system/Roofline.i

# target to preprocess a source file
astra-sim/system/Roofline.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/Roofline.cc.i
.PHONY : astra-sim/system/Roofline.cc.i

astra-sim/system/Roofline.s: astra-sim/system/Roofline.cc.s
.PHONY : astra-sim/system/Roofline.s

# target to generate assembly for a file
astra-sim/system/Roofline.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/Roofline.cc.s
.PHONY : astra-sim/system/Roofline.cc.s

astra-sim/system/SendPacketEventHandlerData.o: astra-sim/system/SendPacketEventHandlerData.cc.o
.PHONY : astra-sim/system/SendPacketEventHandlerData.o

# target to build an object file
astra-sim/system/SendPacketEventHandlerData.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/SendPacketEventHandlerData.cc.o
.PHONY : astra-sim/system/SendPacketEventHandlerData.cc.o

astra-sim/system/SendPacketEventHandlerData.i: astra-sim/system/SendPacketEventHandlerData.cc.i
.PHONY : astra-sim/system/SendPacketEventHandlerData.i

# target to preprocess a source file
astra-sim/system/SendPacketEventHandlerData.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/SendPacketEventHandlerData.cc.i
.PHONY : astra-sim/system/SendPacketEventHandlerData.cc.i

astra-sim/system/SendPacketEventHandlerData.s: astra-sim/system/SendPacketEventHandlerData.cc.s
.PHONY : astra-sim/system/SendPacketEventHandlerData.s

# target to generate assembly for a file
astra-sim/system/SendPacketEventHandlerData.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/SendPacketEventHandlerData.cc.s
.PHONY : astra-sim/system/SendPacketEventHandlerData.cc.s

astra-sim/system/SimRecvCaller.o: astra-sim/system/SimRecvCaller.cc.o
.PHONY : astra-sim/system/SimRecvCaller.o

# target to build an object file
astra-sim/system/SimRecvCaller.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/SimRecvCaller.cc.o
.PHONY : astra-sim/system/SimRecvCaller.cc.o

astra-sim/system/SimRecvCaller.i: astra-sim/system/SimRecvCaller.cc.i
.PHONY : astra-sim/system/SimRecvCaller.i

# target to preprocess a source file
astra-sim/system/SimRecvCaller.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/SimRecvCaller.cc.i
.PHONY : astra-sim/system/SimRecvCaller.cc.i

astra-sim/system/SimRecvCaller.s: astra-sim/system/SimRecvCaller.cc.s
.PHONY : astra-sim/system/SimRecvCaller.s

# target to generate assembly for a file
astra-sim/system/SimRecvCaller.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/SimRecvCaller.cc.s
.PHONY : astra-sim/system/SimRecvCaller.cc.s

astra-sim/system/SimSendCaller.o: astra-sim/system/SimSendCaller.cc.o
.PHONY : astra-sim/system/SimSendCaller.o

# target to build an object file
astra-sim/system/SimSendCaller.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/SimSendCaller.cc.o
.PHONY : astra-sim/system/SimSendCaller.cc.o

astra-sim/system/SimSendCaller.i: astra-sim/system/SimSendCaller.cc.i
.PHONY : astra-sim/system/SimSendCaller.i

# target to preprocess a source file
astra-sim/system/SimSendCaller.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/SimSendCaller.cc.i
.PHONY : astra-sim/system/SimSendCaller.cc.i

astra-sim/system/SimSendCaller.s: astra-sim/system/SimSendCaller.cc.s
.PHONY : astra-sim/system/SimSendCaller.s

# target to generate assembly for a file
astra-sim/system/SimSendCaller.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/SimSendCaller.cc.s
.PHONY : astra-sim/system/SimSendCaller.cc.s

astra-sim/system/StreamBaseline.o: astra-sim/system/StreamBaseline.cc.o
.PHONY : astra-sim/system/StreamBaseline.o

# target to build an object file
astra-sim/system/StreamBaseline.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/StreamBaseline.cc.o
.PHONY : astra-sim/system/StreamBaseline.cc.o

astra-sim/system/StreamBaseline.i: astra-sim/system/StreamBaseline.cc.i
.PHONY : astra-sim/system/StreamBaseline.i

# target to preprocess a source file
astra-sim/system/StreamBaseline.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/StreamBaseline.cc.i
.PHONY : astra-sim/system/StreamBaseline.cc.i

astra-sim/system/StreamBaseline.s: astra-sim/system/StreamBaseline.cc.s
.PHONY : astra-sim/system/StreamBaseline.s

# target to generate assembly for a file
astra-sim/system/StreamBaseline.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/StreamBaseline.cc.s
.PHONY : astra-sim/system/StreamBaseline.cc.s

astra-sim/system/Sys.o: astra-sim/system/Sys.cc.o
.PHONY : astra-sim/system/Sys.o

# target to build an object file
astra-sim/system/Sys.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/Sys.cc.o
.PHONY : astra-sim/system/Sys.cc.o

astra-sim/system/Sys.i: astra-sim/system/Sys.cc.i
.PHONY : astra-sim/system/Sys.i

# target to preprocess a source file
astra-sim/system/Sys.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/Sys.cc.i
.PHONY : astra-sim/system/Sys.cc.i

astra-sim/system/Sys.s: astra-sim/system/Sys.cc.s
.PHONY : astra-sim/system/Sys.s

# target to generate assembly for a file
astra-sim/system/Sys.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/Sys.cc.s
.PHONY : astra-sim/system/Sys.cc.s

astra-sim/system/Usage.o: astra-sim/system/Usage.cc.o
.PHONY : astra-sim/system/Usage.o

# target to build an object file
astra-sim/system/Usage.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/Usage.cc.o
.PHONY : astra-sim/system/Usage.cc.o

astra-sim/system/Usage.i: astra-sim/system/Usage.cc.i
.PHONY : astra-sim/system/Usage.i

# target to preprocess a source file
astra-sim/system/Usage.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/Usage.cc.i
.PHONY : astra-sim/system/Usage.cc.i

astra-sim/system/Usage.s: astra-sim/system/Usage.cc.s
.PHONY : astra-sim/system/Usage.s

# target to generate assembly for a file
astra-sim/system/Usage.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/Usage.cc.s
.PHONY : astra-sim/system/Usage.cc.s

astra-sim/system/UsageTracker.o: astra-sim/system/UsageTracker.cc.o
.PHONY : astra-sim/system/UsageTracker.o

# target to build an object file
astra-sim/system/UsageTracker.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/UsageTracker.cc.o
.PHONY : astra-sim/system/UsageTracker.cc.o

astra-sim/system/UsageTracker.i: astra-sim/system/UsageTracker.cc.i
.PHONY : astra-sim/system/UsageTracker.i

# target to preprocess a source file
astra-sim/system/UsageTracker.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/UsageTracker.cc.i
.PHONY : astra-sim/system/UsageTracker.cc.i

astra-sim/system/UsageTracker.s: astra-sim/system/UsageTracker.cc.s
.PHONY : astra-sim/system/UsageTracker.s

# target to generate assembly for a file
astra-sim/system/UsageTracker.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/UsageTracker.cc.s
.PHONY : astra-sim/system/UsageTracker.cc.s

astra-sim/system/WorkloadLayerHandlerData.o: astra-sim/system/WorkloadLayerHandlerData.cc.o
.PHONY : astra-sim/system/WorkloadLayerHandlerData.o

# target to build an object file
astra-sim/system/WorkloadLayerHandlerData.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/WorkloadLayerHandlerData.cc.o
.PHONY : astra-sim/system/WorkloadLayerHandlerData.cc.o

astra-sim/system/WorkloadLayerHandlerData.i: astra-sim/system/WorkloadLayerHandlerData.cc.i
.PHONY : astra-sim/system/WorkloadLayerHandlerData.i

# target to preprocess a source file
astra-sim/system/WorkloadLayerHandlerData.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/WorkloadLayerHandlerData.cc.i
.PHONY : astra-sim/system/WorkloadLayerHandlerData.cc.i

astra-sim/system/WorkloadLayerHandlerData.s: astra-sim/system/WorkloadLayerHandlerData.cc.s
.PHONY : astra-sim/system/WorkloadLayerHandlerData.s

# target to generate assembly for a file
astra-sim/system/WorkloadLayerHandlerData.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/WorkloadLayerHandlerData.cc.s
.PHONY : astra-sim/system/WorkloadLayerHandlerData.cc.s

astra-sim/system/collective/Algorithm.o: astra-sim/system/collective/Algorithm.cc.o
.PHONY : astra-sim/system/collective/Algorithm.o

# target to build an object file
astra-sim/system/collective/Algorithm.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/collective/Algorithm.cc.o
.PHONY : astra-sim/system/collective/Algorithm.cc.o

astra-sim/system/collective/Algorithm.i: astra-sim/system/collective/Algorithm.cc.i
.PHONY : astra-sim/system/collective/Algorithm.i

# target to preprocess a source file
astra-sim/system/collective/Algorithm.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/collective/Algorithm.cc.i
.PHONY : astra-sim/system/collective/Algorithm.cc.i

astra-sim/system/collective/Algorithm.s: astra-sim/system/collective/Algorithm.cc.s
.PHONY : astra-sim/system/collective/Algorithm.s

# target to generate assembly for a file
astra-sim/system/collective/Algorithm.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/collective/Algorithm.cc.s
.PHONY : astra-sim/system/collective/Algorithm.cc.s

astra-sim/system/collective/AllToAll.o: astra-sim/system/collective/AllToAll.cc.o
.PHONY : astra-sim/system/collective/AllToAll.o

# target to build an object file
astra-sim/system/collective/AllToAll.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/collective/AllToAll.cc.o
.PHONY : astra-sim/system/collective/AllToAll.cc.o

astra-sim/system/collective/AllToAll.i: astra-sim/system/collective/AllToAll.cc.i
.PHONY : astra-sim/system/collective/AllToAll.i

# target to preprocess a source file
astra-sim/system/collective/AllToAll.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/collective/AllToAll.cc.i
.PHONY : astra-sim/system/collective/AllToAll.cc.i

astra-sim/system/collective/AllToAll.s: astra-sim/system/collective/AllToAll.cc.s
.PHONY : astra-sim/system/collective/AllToAll.s

# target to generate assembly for a file
astra-sim/system/collective/AllToAll.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/collective/AllToAll.cc.s
.PHONY : astra-sim/system/collective/AllToAll.cc.s

astra-sim/system/collective/ChakraImpl.o: astra-sim/system/collective/ChakraImpl.cc.o
.PHONY : astra-sim/system/collective/ChakraImpl.o

# target to build an object file
astra-sim/system/collective/ChakraImpl.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/collective/ChakraImpl.cc.o
.PHONY : astra-sim/system/collective/ChakraImpl.cc.o

astra-sim/system/collective/ChakraImpl.i: astra-sim/system/collective/ChakraImpl.cc.i
.PHONY : astra-sim/system/collective/ChakraImpl.i

# target to preprocess a source file
astra-sim/system/collective/ChakraImpl.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/collective/ChakraImpl.cc.i
.PHONY : astra-sim/system/collective/ChakraImpl.cc.i

astra-sim/system/collective/ChakraImpl.s: astra-sim/system/collective/ChakraImpl.cc.s
.PHONY : astra-sim/system/collective/ChakraImpl.s

# target to generate assembly for a file
astra-sim/system/collective/ChakraImpl.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/collective/ChakraImpl.cc.s
.PHONY : astra-sim/system/collective/ChakraImpl.cc.s

astra-sim/system/collective/DoubleBinaryTreeAllReduce.o: astra-sim/system/collective/DoubleBinaryTreeAllReduce.cc.o
.PHONY : astra-sim/system/collective/DoubleBinaryTreeAllReduce.o

# target to build an object file
astra-sim/system/collective/DoubleBinaryTreeAllReduce.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/collective/DoubleBinaryTreeAllReduce.cc.o
.PHONY : astra-sim/system/collective/DoubleBinaryTreeAllReduce.cc.o

astra-sim/system/collective/DoubleBinaryTreeAllReduce.i: astra-sim/system/collective/DoubleBinaryTreeAllReduce.cc.i
.PHONY : astra-sim/system/collective/DoubleBinaryTreeAllReduce.i

# target to preprocess a source file
astra-sim/system/collective/DoubleBinaryTreeAllReduce.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/collective/DoubleBinaryTreeAllReduce.cc.i
.PHONY : astra-sim/system/collective/DoubleBinaryTreeAllReduce.cc.i

astra-sim/system/collective/DoubleBinaryTreeAllReduce.s: astra-sim/system/collective/DoubleBinaryTreeAllReduce.cc.s
.PHONY : astra-sim/system/collective/DoubleBinaryTreeAllReduce.s

# target to generate assembly for a file
astra-sim/system/collective/DoubleBinaryTreeAllReduce.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/collective/DoubleBinaryTreeAllReduce.cc.s
.PHONY : astra-sim/system/collective/DoubleBinaryTreeAllReduce.cc.s

astra-sim/system/collective/HalvingDoubling.o: astra-sim/system/collective/HalvingDoubling.cc.o
.PHONY : astra-sim/system/collective/HalvingDoubling.o

# target to build an object file
astra-sim/system/collective/HalvingDoubling.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/collective/HalvingDoubling.cc.o
.PHONY : astra-sim/system/collective/HalvingDoubling.cc.o

astra-sim/system/collective/HalvingDoubling.i: astra-sim/system/collective/HalvingDoubling.cc.i
.PHONY : astra-sim/system/collective/HalvingDoubling.i

# target to preprocess a source file
astra-sim/system/collective/HalvingDoubling.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/collective/HalvingDoubling.cc.i
.PHONY : astra-sim/system/collective/HalvingDoubling.cc.i

astra-sim/system/collective/HalvingDoubling.s: astra-sim/system/collective/HalvingDoubling.cc.s
.PHONY : astra-sim/system/collective/HalvingDoubling.s

# target to generate assembly for a file
astra-sim/system/collective/HalvingDoubling.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/collective/HalvingDoubling.cc.s
.PHONY : astra-sim/system/collective/HalvingDoubling.cc.s

astra-sim/system/collective/Ring.o: astra-sim/system/collective/Ring.cc.o
.PHONY : astra-sim/system/collective/Ring.o

# target to build an object file
astra-sim/system/collective/Ring.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/collective/Ring.cc.o
.PHONY : astra-sim/system/collective/Ring.cc.o

astra-sim/system/collective/Ring.i: astra-sim/system/collective/Ring.cc.i
.PHONY : astra-sim/system/collective/Ring.i

# target to preprocess a source file
astra-sim/system/collective/Ring.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/collective/Ring.cc.i
.PHONY : astra-sim/system/collective/Ring.cc.i

astra-sim/system/collective/Ring.s: astra-sim/system/collective/Ring.cc.s
.PHONY : astra-sim/system/collective/Ring.s

# target to generate assembly for a file
astra-sim/system/collective/Ring.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/collective/Ring.cc.s
.PHONY : astra-sim/system/collective/Ring.cc.s

astra-sim/system/scheduling/OfflineGreedy.o: astra-sim/system/scheduling/OfflineGreedy.cc.o
.PHONY : astra-sim/system/scheduling/OfflineGreedy.o

# target to build an object file
astra-sim/system/scheduling/OfflineGreedy.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/scheduling/OfflineGreedy.cc.o
.PHONY : astra-sim/system/scheduling/OfflineGreedy.cc.o

astra-sim/system/scheduling/OfflineGreedy.i: astra-sim/system/scheduling/OfflineGreedy.cc.i
.PHONY : astra-sim/system/scheduling/OfflineGreedy.i

# target to preprocess a source file
astra-sim/system/scheduling/OfflineGreedy.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/scheduling/OfflineGreedy.cc.i
.PHONY : astra-sim/system/scheduling/OfflineGreedy.cc.i

astra-sim/system/scheduling/OfflineGreedy.s: astra-sim/system/scheduling/OfflineGreedy.cc.s
.PHONY : astra-sim/system/scheduling/OfflineGreedy.s

# target to generate assembly for a file
astra-sim/system/scheduling/OfflineGreedy.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/scheduling/OfflineGreedy.cc.s
.PHONY : astra-sim/system/scheduling/OfflineGreedy.cc.s

astra-sim/system/topology/BinaryTree.o: astra-sim/system/topology/BinaryTree.cc.o
.PHONY : astra-sim/system/topology/BinaryTree.o

# target to build an object file
astra-sim/system/topology/BinaryTree.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/topology/BinaryTree.cc.o
.PHONY : astra-sim/system/topology/BinaryTree.cc.o

astra-sim/system/topology/BinaryTree.i: astra-sim/system/topology/BinaryTree.cc.i
.PHONY : astra-sim/system/topology/BinaryTree.i

# target to preprocess a source file
astra-sim/system/topology/BinaryTree.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/topology/BinaryTree.cc.i
.PHONY : astra-sim/system/topology/BinaryTree.cc.i

astra-sim/system/topology/BinaryTree.s: astra-sim/system/topology/BinaryTree.cc.s
.PHONY : astra-sim/system/topology/BinaryTree.s

# target to generate assembly for a file
astra-sim/system/topology/BinaryTree.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/topology/BinaryTree.cc.s
.PHONY : astra-sim/system/topology/BinaryTree.cc.s

astra-sim/system/topology/DoubleBinaryTreeTopology.o: astra-sim/system/topology/DoubleBinaryTreeTopology.cc.o
.PHONY : astra-sim/system/topology/DoubleBinaryTreeTopology.o

# target to build an object file
astra-sim/system/topology/DoubleBinaryTreeTopology.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/topology/DoubleBinaryTreeTopology.cc.o
.PHONY : astra-sim/system/topology/DoubleBinaryTreeTopology.cc.o

astra-sim/system/topology/DoubleBinaryTreeTopology.i: astra-sim/system/topology/DoubleBinaryTreeTopology.cc.i
.PHONY : astra-sim/system/topology/DoubleBinaryTreeTopology.i

# target to preprocess a source file
astra-sim/system/topology/DoubleBinaryTreeTopology.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/topology/DoubleBinaryTreeTopology.cc.i
.PHONY : astra-sim/system/topology/DoubleBinaryTreeTopology.cc.i

astra-sim/system/topology/DoubleBinaryTreeTopology.s: astra-sim/system/topology/DoubleBinaryTreeTopology.cc.s
.PHONY : astra-sim/system/topology/DoubleBinaryTreeTopology.s

# target to generate assembly for a file
astra-sim/system/topology/DoubleBinaryTreeTopology.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/topology/DoubleBinaryTreeTopology.cc.s
.PHONY : astra-sim/system/topology/DoubleBinaryTreeTopology.cc.s

astra-sim/system/topology/GeneralComplexTopology.o: astra-sim/system/topology/GeneralComplexTopology.cc.o
.PHONY : astra-sim/system/topology/GeneralComplexTopology.o

# target to build an object file
astra-sim/system/topology/GeneralComplexTopology.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/topology/GeneralComplexTopology.cc.o
.PHONY : astra-sim/system/topology/GeneralComplexTopology.cc.o

astra-sim/system/topology/GeneralComplexTopology.i: astra-sim/system/topology/GeneralComplexTopology.cc.i
.PHONY : astra-sim/system/topology/GeneralComplexTopology.i

# target to preprocess a source file
astra-sim/system/topology/GeneralComplexTopology.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/topology/GeneralComplexTopology.cc.i
.PHONY : astra-sim/system/topology/GeneralComplexTopology.cc.i

astra-sim/system/topology/GeneralComplexTopology.s: astra-sim/system/topology/GeneralComplexTopology.cc.s
.PHONY : astra-sim/system/topology/GeneralComplexTopology.s

# target to generate assembly for a file
astra-sim/system/topology/GeneralComplexTopology.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/topology/GeneralComplexTopology.cc.s
.PHONY : astra-sim/system/topology/GeneralComplexTopology.cc.s

astra-sim/system/topology/LocalRingGlobalBinaryTree.o: astra-sim/system/topology/LocalRingGlobalBinaryTree.cc.o
.PHONY : astra-sim/system/topology/LocalRingGlobalBinaryTree.o

# target to build an object file
astra-sim/system/topology/LocalRingGlobalBinaryTree.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/topology/LocalRingGlobalBinaryTree.cc.o
.PHONY : astra-sim/system/topology/LocalRingGlobalBinaryTree.cc.o

astra-sim/system/topology/LocalRingGlobalBinaryTree.i: astra-sim/system/topology/LocalRingGlobalBinaryTree.cc.i
.PHONY : astra-sim/system/topology/LocalRingGlobalBinaryTree.i

# target to preprocess a source file
astra-sim/system/topology/LocalRingGlobalBinaryTree.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/topology/LocalRingGlobalBinaryTree.cc.i
.PHONY : astra-sim/system/topology/LocalRingGlobalBinaryTree.cc.i

astra-sim/system/topology/LocalRingGlobalBinaryTree.s: astra-sim/system/topology/LocalRingGlobalBinaryTree.cc.s
.PHONY : astra-sim/system/topology/LocalRingGlobalBinaryTree.s

# target to generate assembly for a file
astra-sim/system/topology/LocalRingGlobalBinaryTree.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/topology/LocalRingGlobalBinaryTree.cc.s
.PHONY : astra-sim/system/topology/LocalRingGlobalBinaryTree.cc.s

astra-sim/system/topology/LocalRingNodeA2AGlobalDBT.o: astra-sim/system/topology/LocalRingNodeA2AGlobalDBT.cc.o
.PHONY : astra-sim/system/topology/LocalRingNodeA2AGlobalDBT.o

# target to build an object file
astra-sim/system/topology/LocalRingNodeA2AGlobalDBT.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/topology/LocalRingNodeA2AGlobalDBT.cc.o
.PHONY : astra-sim/system/topology/LocalRingNodeA2AGlobalDBT.cc.o

astra-sim/system/topology/LocalRingNodeA2AGlobalDBT.i: astra-sim/system/topology/LocalRingNodeA2AGlobalDBT.cc.i
.PHONY : astra-sim/system/topology/LocalRingNodeA2AGlobalDBT.i

# target to preprocess a source file
astra-sim/system/topology/LocalRingNodeA2AGlobalDBT.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/topology/LocalRingNodeA2AGlobalDBT.cc.i
.PHONY : astra-sim/system/topology/LocalRingNodeA2AGlobalDBT.cc.i

astra-sim/system/topology/LocalRingNodeA2AGlobalDBT.s: astra-sim/system/topology/LocalRingNodeA2AGlobalDBT.cc.s
.PHONY : astra-sim/system/topology/LocalRingNodeA2AGlobalDBT.s

# target to generate assembly for a file
astra-sim/system/topology/LocalRingNodeA2AGlobalDBT.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/topology/LocalRingNodeA2AGlobalDBT.cc.s
.PHONY : astra-sim/system/topology/LocalRingNodeA2AGlobalDBT.cc.s

astra-sim/system/topology/Node.o: astra-sim/system/topology/Node.cc.o
.PHONY : astra-sim/system/topology/Node.o

# target to build an object file
astra-sim/system/topology/Node.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/topology/Node.cc.o
.PHONY : astra-sim/system/topology/Node.cc.o

astra-sim/system/topology/Node.i: astra-sim/system/topology/Node.cc.i
.PHONY : astra-sim/system/topology/Node.i

# target to preprocess a source file
astra-sim/system/topology/Node.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/topology/Node.cc.i
.PHONY : astra-sim/system/topology/Node.cc.i

astra-sim/system/topology/Node.s: astra-sim/system/topology/Node.cc.s
.PHONY : astra-sim/system/topology/Node.s

# target to generate assembly for a file
astra-sim/system/topology/Node.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/topology/Node.cc.s
.PHONY : astra-sim/system/topology/Node.cc.s

astra-sim/system/topology/RingTopology.o: astra-sim/system/topology/RingTopology.cc.o
.PHONY : astra-sim/system/topology/RingTopology.o

# target to build an object file
astra-sim/system/topology/RingTopology.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/topology/RingTopology.cc.o
.PHONY : astra-sim/system/topology/RingTopology.cc.o

astra-sim/system/topology/RingTopology.i: astra-sim/system/topology/RingTopology.cc.i
.PHONY : astra-sim/system/topology/RingTopology.i

# target to preprocess a source file
astra-sim/system/topology/RingTopology.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/topology/RingTopology.cc.i
.PHONY : astra-sim/system/topology/RingTopology.cc.i

astra-sim/system/topology/RingTopology.s: astra-sim/system/topology/RingTopology.cc.s
.PHONY : astra-sim/system/topology/RingTopology.s

# target to generate assembly for a file
astra-sim/system/topology/RingTopology.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/topology/RingTopology.cc.s
.PHONY : astra-sim/system/topology/RingTopology.cc.s

astra-sim/system/topology/Torus3D.o: astra-sim/system/topology/Torus3D.cc.o
.PHONY : astra-sim/system/topology/Torus3D.o

# target to build an object file
astra-sim/system/topology/Torus3D.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/topology/Torus3D.cc.o
.PHONY : astra-sim/system/topology/Torus3D.cc.o

astra-sim/system/topology/Torus3D.i: astra-sim/system/topology/Torus3D.cc.i
.PHONY : astra-sim/system/topology/Torus3D.i

# target to preprocess a source file
astra-sim/system/topology/Torus3D.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/topology/Torus3D.cc.i
.PHONY : astra-sim/system/topology/Torus3D.cc.i

astra-sim/system/topology/Torus3D.s: astra-sim/system/topology/Torus3D.cc.s
.PHONY : astra-sim/system/topology/Torus3D.s

# target to generate assembly for a file
astra-sim/system/topology/Torus3D.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/system/topology/Torus3D.cc.s
.PHONY : astra-sim/system/topology/Torus3D.cc.s

astra-sim/workload/HardwareResource.o: astra-sim/workload/HardwareResource.cc.o
.PHONY : astra-sim/workload/HardwareResource.o

# target to build an object file
astra-sim/workload/HardwareResource.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/workload/HardwareResource.cc.o
.PHONY : astra-sim/workload/HardwareResource.cc.o

astra-sim/workload/HardwareResource.i: astra-sim/workload/HardwareResource.cc.i
.PHONY : astra-sim/workload/HardwareResource.i

# target to preprocess a source file
astra-sim/workload/HardwareResource.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/workload/HardwareResource.cc.i
.PHONY : astra-sim/workload/HardwareResource.cc.i

astra-sim/workload/HardwareResource.s: astra-sim/workload/HardwareResource.cc.s
.PHONY : astra-sim/workload/HardwareResource.s

# target to generate assembly for a file
astra-sim/workload/HardwareResource.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/workload/HardwareResource.cc.s
.PHONY : astra-sim/workload/HardwareResource.cc.s

astra-sim/workload/Workload.o: astra-sim/workload/Workload.cc.o
.PHONY : astra-sim/workload/Workload.o

# target to build an object file
astra-sim/workload/Workload.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/workload/Workload.cc.o
.PHONY : astra-sim/workload/Workload.cc.o

astra-sim/workload/Workload.i: astra-sim/workload/Workload.cc.i
.PHONY : astra-sim/workload/Workload.i

# target to preprocess a source file
astra-sim/workload/Workload.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/workload/Workload.cc.i
.PHONY : astra-sim/workload/Workload.cc.i

astra-sim/workload/Workload.s: astra-sim/workload/Workload.cc.s
.PHONY : astra-sim/workload/Workload.s

# target to generate assembly for a file
astra-sim/workload/Workload.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/astra-sim/workload/Workload.cc.s
.PHONY : astra-sim/workload/Workload.cc.s

extern/graph_frontend/chakra/schema/protobuf/et_def.pb.o: extern/graph_frontend/chakra/schema/protobuf/et_def.pb.cc.o
.PHONY : extern/graph_frontend/chakra/schema/protobuf/et_def.pb.o

# target to build an object file
extern/graph_frontend/chakra/schema/protobuf/et_def.pb.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/extern/graph_frontend/chakra/schema/protobuf/et_def.pb.cc.o
.PHONY : extern/graph_frontend/chakra/schema/protobuf/et_def.pb.cc.o

extern/graph_frontend/chakra/schema/protobuf/et_def.pb.i: extern/graph_frontend/chakra/schema/protobuf/et_def.pb.cc.i
.PHONY : extern/graph_frontend/chakra/schema/protobuf/et_def.pb.i

# target to preprocess a source file
extern/graph_frontend/chakra/schema/protobuf/et_def.pb.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/extern/graph_frontend/chakra/schema/protobuf/et_def.pb.cc.i
.PHONY : extern/graph_frontend/chakra/schema/protobuf/et_def.pb.cc.i

extern/graph_frontend/chakra/schema/protobuf/et_def.pb.s: extern/graph_frontend/chakra/schema/protobuf/et_def.pb.cc.s
.PHONY : extern/graph_frontend/chakra/schema/protobuf/et_def.pb.s

# target to generate assembly for a file
extern/graph_frontend/chakra/schema/protobuf/et_def.pb.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/extern/graph_frontend/chakra/schema/protobuf/et_def.pb.cc.s
.PHONY : extern/graph_frontend/chakra/schema/protobuf/et_def.pb.cc.s

extern/graph_frontend/chakra/src/feeder/et_feeder.o: extern/graph_frontend/chakra/src/feeder/et_feeder.cpp.o
.PHONY : extern/graph_frontend/chakra/src/feeder/et_feeder.o

# target to build an object file
extern/graph_frontend/chakra/src/feeder/et_feeder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/extern/graph_frontend/chakra/src/feeder/et_feeder.cpp.o
.PHONY : extern/graph_frontend/chakra/src/feeder/et_feeder.cpp.o

extern/graph_frontend/chakra/src/feeder/et_feeder.i: extern/graph_frontend/chakra/src/feeder/et_feeder.cpp.i
.PHONY : extern/graph_frontend/chakra/src/feeder/et_feeder.i

# target to preprocess a source file
extern/graph_frontend/chakra/src/feeder/et_feeder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/extern/graph_frontend/chakra/src/feeder/et_feeder.cpp.i
.PHONY : extern/graph_frontend/chakra/src/feeder/et_feeder.cpp.i

extern/graph_frontend/chakra/src/feeder/et_feeder.s: extern/graph_frontend/chakra/src/feeder/et_feeder.cpp.s
.PHONY : extern/graph_frontend/chakra/src/feeder/et_feeder.s

# target to generate assembly for a file
extern/graph_frontend/chakra/src/feeder/et_feeder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/extern/graph_frontend/chakra/src/feeder/et_feeder.cpp.s
.PHONY : extern/graph_frontend/chakra/src/feeder/et_feeder.cpp.s

extern/graph_frontend/chakra/src/feeder/et_feeder_node.o: extern/graph_frontend/chakra/src/feeder/et_feeder_node.cpp.o
.PHONY : extern/graph_frontend/chakra/src/feeder/et_feeder_node.o

# target to build an object file
extern/graph_frontend/chakra/src/feeder/et_feeder_node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/extern/graph_frontend/chakra/src/feeder/et_feeder_node.cpp.o
.PHONY : extern/graph_frontend/chakra/src/feeder/et_feeder_node.cpp.o

extern/graph_frontend/chakra/src/feeder/et_feeder_node.i: extern/graph_frontend/chakra/src/feeder/et_feeder_node.cpp.i
.PHONY : extern/graph_frontend/chakra/src/feeder/et_feeder_node.i

# target to preprocess a source file
extern/graph_frontend/chakra/src/feeder/et_feeder_node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/extern/graph_frontend/chakra/src/feeder/et_feeder_node.cpp.i
.PHONY : extern/graph_frontend/chakra/src/feeder/et_feeder_node.cpp.i

extern/graph_frontend/chakra/src/feeder/et_feeder_node.s: extern/graph_frontend/chakra/src/feeder/et_feeder_node.cpp.s
.PHONY : extern/graph_frontend/chakra/src/feeder/et_feeder_node.s

# target to generate assembly for a file
extern/graph_frontend/chakra/src/feeder/et_feeder_node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/extern/graph_frontend/chakra/src/feeder/et_feeder_node.cpp.s
.PHONY : extern/graph_frontend/chakra/src/feeder/et_feeder_node.cpp.s

extern/graph_frontend/chakra/src/third_party/utils/protoio.o: extern/graph_frontend/chakra/src/third_party/utils/protoio.cc.o
.PHONY : extern/graph_frontend/chakra/src/third_party/utils/protoio.o

# target to build an object file
extern/graph_frontend/chakra/src/third_party/utils/protoio.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/extern/graph_frontend/chakra/src/third_party/utils/protoio.cc.o
.PHONY : extern/graph_frontend/chakra/src/third_party/utils/protoio.cc.o

extern/graph_frontend/chakra/src/third_party/utils/protoio.i: extern/graph_frontend/chakra/src/third_party/utils/protoio.cc.i
.PHONY : extern/graph_frontend/chakra/src/third_party/utils/protoio.i

# target to preprocess a source file
extern/graph_frontend/chakra/src/third_party/utils/protoio.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/extern/graph_frontend/chakra/src/third_party/utils/protoio.cc.i
.PHONY : extern/graph_frontend/chakra/src/third_party/utils/protoio.cc.i

extern/graph_frontend/chakra/src/third_party/utils/protoio.s: extern/graph_frontend/chakra/src/third_party/utils/protoio.cc.s
.PHONY : extern/graph_frontend/chakra/src/third_party/utils/protoio.s

# target to generate assembly for a file
extern/graph_frontend/chakra/src/third_party/utils/protoio.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/extern/graph_frontend/chakra/src/third_party/utils/protoio.cc.s
.PHONY : extern/graph_frontend/chakra/src/third_party/utils/protoio.cc.s

extern/remote_memory_backend/analytical/AnalyticalRemoteMemory.o: extern/remote_memory_backend/analytical/AnalyticalRemoteMemory.cc.o
.PHONY : extern/remote_memory_backend/analytical/AnalyticalRemoteMemory.o

# target to build an object file
extern/remote_memory_backend/analytical/AnalyticalRemoteMemory.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/extern/remote_memory_backend/analytical/AnalyticalRemoteMemory.cc.o
.PHONY : extern/remote_memory_backend/analytical/AnalyticalRemoteMemory.cc.o

extern/remote_memory_backend/analytical/AnalyticalRemoteMemory.i: extern/remote_memory_backend/analytical/AnalyticalRemoteMemory.cc.i
.PHONY : extern/remote_memory_backend/analytical/AnalyticalRemoteMemory.i

# target to preprocess a source file
extern/remote_memory_backend/analytical/AnalyticalRemoteMemory.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/extern/remote_memory_backend/analytical/AnalyticalRemoteMemory.cc.i
.PHONY : extern/remote_memory_backend/analytical/AnalyticalRemoteMemory.cc.i

extern/remote_memory_backend/analytical/AnalyticalRemoteMemory.s: extern/remote_memory_backend/analytical/AnalyticalRemoteMemory.cc.s
.PHONY : extern/remote_memory_backend/analytical/AnalyticalRemoteMemory.s

# target to generate assembly for a file
extern/remote_memory_backend/analytical/AnalyticalRemoteMemory.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AstraSim.dir/build.make CMakeFiles/AstraSim.dir/extern/remote_memory_backend/analytical/AnalyticalRemoteMemory.cc.s
.PHONY : extern/remote_memory_backend/analytical/AnalyticalRemoteMemory.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... AstraSim"
	@echo "... fmt"
	@echo "... spdlog"
	@echo "... astra-sim/common/Logging.o"
	@echo "... astra-sim/common/Logging.i"
	@echo "... astra-sim/common/Logging.s"
	@echo "... astra-sim/system/BaseStream.o"
	@echo "... astra-sim/system/BaseStream.i"
	@echo "... astra-sim/system/BaseStream.s"
	@echo "... astra-sim/system/BasicEventHandlerData.o"
	@echo "... astra-sim/system/BasicEventHandlerData.i"
	@echo "... astra-sim/system/BasicEventHandlerData.s"
	@echo "... astra-sim/system/CSVWriter.o"
	@echo "... astra-sim/system/CSVWriter.i"
	@echo "... astra-sim/system/CSVWriter.s"
	@echo "... astra-sim/system/CollectivePhase.o"
	@echo "... astra-sim/system/CollectivePhase.i"
	@echo "... astra-sim/system/CollectivePhase.s"
	@echo "... astra-sim/system/CollectivePlan.o"
	@echo "... astra-sim/system/CollectivePlan.i"
	@echo "... astra-sim/system/CollectivePlan.s"
	@echo "... astra-sim/system/CommunicatorGroup.o"
	@echo "... astra-sim/system/CommunicatorGroup.i"
	@echo "... astra-sim/system/CommunicatorGroup.s"
	@echo "... astra-sim/system/DataSet.o"
	@echo "... astra-sim/system/DataSet.i"
	@echo "... astra-sim/system/DataSet.s"
	@echo "... astra-sim/system/LogGP.o"
	@echo "... astra-sim/system/LogGP.i"
	@echo "... astra-sim/system/LogGP.s"
	@echo "... astra-sim/system/MemBus.o"
	@echo "... astra-sim/system/MemBus.i"
	@echo "... astra-sim/system/MemBus.s"
	@echo "... astra-sim/system/MemEventHandlerData.o"
	@echo "... astra-sim/system/MemEventHandlerData.i"
	@echo "... astra-sim/system/MemEventHandlerData.s"
	@echo "... astra-sim/system/MemMovRequest.o"
	@echo "... astra-sim/system/MemMovRequest.i"
	@echo "... astra-sim/system/MemMovRequest.s"
	@echo "... astra-sim/system/MyPacket.o"
	@echo "... astra-sim/system/MyPacket.i"
	@echo "... astra-sim/system/MyPacket.s"
	@echo "... astra-sim/system/PacketBundle.o"
	@echo "... astra-sim/system/PacketBundle.i"
	@echo "... astra-sim/system/PacketBundle.s"
	@echo "... astra-sim/system/QueueLevelHandler.o"
	@echo "... astra-sim/system/QueueLevelHandler.i"
	@echo "... astra-sim/system/QueueLevelHandler.s"
	@echo "... astra-sim/system/QueueLevels.o"
	@echo "... astra-sim/system/QueueLevels.i"
	@echo "... astra-sim/system/QueueLevels.s"
	@echo "... astra-sim/system/RecvPacketEventHandlerData.o"
	@echo "... astra-sim/system/RecvPacketEventHandlerData.i"
	@echo "... astra-sim/system/RecvPacketEventHandlerData.s"
	@echo "... astra-sim/system/RendezvousRecvData.o"
	@echo "... astra-sim/system/RendezvousRecvData.i"
	@echo "... astra-sim/system/RendezvousRecvData.s"
	@echo "... astra-sim/system/RendezvousSendData.o"
	@echo "... astra-sim/system/RendezvousSendData.i"
	@echo "... astra-sim/system/RendezvousSendData.s"
	@echo "... astra-sim/system/Roofline.o"
	@echo "... astra-sim/system/Roofline.i"
	@echo "... astra-sim/system/Roofline.s"
	@echo "... astra-sim/system/SendPacketEventHandlerData.o"
	@echo "... astra-sim/system/SendPacketEventHandlerData.i"
	@echo "... astra-sim/system/SendPacketEventHandlerData.s"
	@echo "... astra-sim/system/SimRecvCaller.o"
	@echo "... astra-sim/system/SimRecvCaller.i"
	@echo "... astra-sim/system/SimRecvCaller.s"
	@echo "... astra-sim/system/SimSendCaller.o"
	@echo "... astra-sim/system/SimSendCaller.i"
	@echo "... astra-sim/system/SimSendCaller.s"
	@echo "... astra-sim/system/StreamBaseline.o"
	@echo "... astra-sim/system/StreamBaseline.i"
	@echo "... astra-sim/system/StreamBaseline.s"
	@echo "... astra-sim/system/Sys.o"
	@echo "... astra-sim/system/Sys.i"
	@echo "... astra-sim/system/Sys.s"
	@echo "... astra-sim/system/Usage.o"
	@echo "... astra-sim/system/Usage.i"
	@echo "... astra-sim/system/Usage.s"
	@echo "... astra-sim/system/UsageTracker.o"
	@echo "... astra-sim/system/UsageTracker.i"
	@echo "... astra-sim/system/UsageTracker.s"
	@echo "... astra-sim/system/WorkloadLayerHandlerData.o"
	@echo "... astra-sim/system/WorkloadLayerHandlerData.i"
	@echo "... astra-sim/system/WorkloadLayerHandlerData.s"
	@echo "... astra-sim/system/collective/Algorithm.o"
	@echo "... astra-sim/system/collective/Algorithm.i"
	@echo "... astra-sim/system/collective/Algorithm.s"
	@echo "... astra-sim/system/collective/AllToAll.o"
	@echo "... astra-sim/system/collective/AllToAll.i"
	@echo "... astra-sim/system/collective/AllToAll.s"
	@echo "... astra-sim/system/collective/ChakraImpl.o"
	@echo "... astra-sim/system/collective/ChakraImpl.i"
	@echo "... astra-sim/system/collective/ChakraImpl.s"
	@echo "... astra-sim/system/collective/DoubleBinaryTreeAllReduce.o"
	@echo "... astra-sim/system/collective/DoubleBinaryTreeAllReduce.i"
	@echo "... astra-sim/system/collective/DoubleBinaryTreeAllReduce.s"
	@echo "... astra-sim/system/collective/HalvingDoubling.o"
	@echo "... astra-sim/system/collective/HalvingDoubling.i"
	@echo "... astra-sim/system/collective/HalvingDoubling.s"
	@echo "... astra-sim/system/collective/Ring.o"
	@echo "... astra-sim/system/collective/Ring.i"
	@echo "... astra-sim/system/collective/Ring.s"
	@echo "... astra-sim/system/scheduling/OfflineGreedy.o"
	@echo "... astra-sim/system/scheduling/OfflineGreedy.i"
	@echo "... astra-sim/system/scheduling/OfflineGreedy.s"
	@echo "... astra-sim/system/topology/BinaryTree.o"
	@echo "... astra-sim/system/topology/BinaryTree.i"
	@echo "... astra-sim/system/topology/BinaryTree.s"
	@echo "... astra-sim/system/topology/DoubleBinaryTreeTopology.o"
	@echo "... astra-sim/system/topology/DoubleBinaryTreeTopology.i"
	@echo "... astra-sim/system/topology/DoubleBinaryTreeTopology.s"
	@echo "... astra-sim/system/topology/GeneralComplexTopology.o"
	@echo "... astra-sim/system/topology/GeneralComplexTopology.i"
	@echo "... astra-sim/system/topology/GeneralComplexTopology.s"
	@echo "... astra-sim/system/topology/LocalRingGlobalBinaryTree.o"
	@echo "... astra-sim/system/topology/LocalRingGlobalBinaryTree.i"
	@echo "... astra-sim/system/topology/LocalRingGlobalBinaryTree.s"
	@echo "... astra-sim/system/topology/LocalRingNodeA2AGlobalDBT.o"
	@echo "... astra-sim/system/topology/LocalRingNodeA2AGlobalDBT.i"
	@echo "... astra-sim/system/topology/LocalRingNodeA2AGlobalDBT.s"
	@echo "... astra-sim/system/topology/Node.o"
	@echo "... astra-sim/system/topology/Node.i"
	@echo "... astra-sim/system/topology/Node.s"
	@echo "... astra-sim/system/topology/RingTopology.o"
	@echo "... astra-sim/system/topology/RingTopology.i"
	@echo "... astra-sim/system/topology/RingTopology.s"
	@echo "... astra-sim/system/topology/Torus3D.o"
	@echo "... astra-sim/system/topology/Torus3D.i"
	@echo "... astra-sim/system/topology/Torus3D.s"
	@echo "... astra-sim/workload/HardwareResource.o"
	@echo "... astra-sim/workload/HardwareResource.i"
	@echo "... astra-sim/workload/HardwareResource.s"
	@echo "... astra-sim/workload/Workload.o"
	@echo "... astra-sim/workload/Workload.i"
	@echo "... astra-sim/workload/Workload.s"
	@echo "... extern/graph_frontend/chakra/schema/protobuf/et_def.pb.o"
	@echo "... extern/graph_frontend/chakra/schema/protobuf/et_def.pb.i"
	@echo "... extern/graph_frontend/chakra/schema/protobuf/et_def.pb.s"
	@echo "... extern/graph_frontend/chakra/src/feeder/et_feeder.o"
	@echo "... extern/graph_frontend/chakra/src/feeder/et_feeder.i"
	@echo "... extern/graph_frontend/chakra/src/feeder/et_feeder.s"
	@echo "... extern/graph_frontend/chakra/src/feeder/et_feeder_node.o"
	@echo "... extern/graph_frontend/chakra/src/feeder/et_feeder_node.i"
	@echo "... extern/graph_frontend/chakra/src/feeder/et_feeder_node.s"
	@echo "... extern/graph_frontend/chakra/src/third_party/utils/protoio.o"
	@echo "... extern/graph_frontend/chakra/src/third_party/utils/protoio.i"
	@echo "... extern/graph_frontend/chakra/src/third_party/utils/protoio.s"
	@echo "... extern/remote_memory_backend/analytical/AnalyticalRemoteMemory.o"
	@echo "... extern/remote_memory_backend/analytical/AnalyticalRemoteMemory.i"
	@echo "... extern/remote_memory_backend/analytical/AnalyticalRemoteMemory.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

